# Generated by Django 2.0.4 on 2018-11-15 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Color')),
            ],
        ),
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='scent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Scent'),
        ),
    ]
