# Generated by Django 2.0.4 on 2018-11-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20181115_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='color',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='scent',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='scent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Scent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='type_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Product_Type'),
            preserve_default=False,
        ),
    ]
