# Generated by Django 2.0.4 on 2018-11-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20181115_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_type',
            name='min_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('light-green', 'light-green'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('brown', 'brown'), ('tan', 'tan'), ('whitecream', 'whitecream'), ('orange', 'orange'), ('purple', 'purple')], max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='scent_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainsite.Scent'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='name',
            field=models.CharField(choices=[('cinnamon roll votive', 'cinnamon roll votive'), ('cinnamon roll', 'cinnamon roll'), ('cinnamon roll with burn dishpie', 'cinnamon roll with burn dishpie'), ('candle in jar', 'candle in jar'), ('candle melts', 'candle melts')], max_length=60),
        ),
        migrations.AlterField(
            model_name='scent',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='scent',
            name='name',
            field=models.CharField(choices=[('pumpkin', 'pumpkin'), ('mixed berry', 'mixed berry'), ('sampler', 'sampler'), ('strawberry', 'strawberry')], max_length=40),
        ),
    ]
