# Generated by Django 2.0.4 on 2018-11-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20181116_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prod_img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='min_order',
            field=models.IntegerField(verbose_name='Minimum Number of this Product'),
        ),
        migrations.AlterField(
            model_name='product_type',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price per Item'),
        ),
        migrations.AlterField(
            model_name='scent',
            name='name',
            field=models.CharField(choices=[('pumpkin', 'pumpkin'), ('mixed berry', 'mixed berry'), ('sampler', 'sampler'), ('strawberry', 'strawberry'), ('apple', 'apple'), ('apple-cinnamon', 'apple-cinnamon'), ('cinnamon roll', 'cinnamon roll')], max_length=40),
        ),
    ]
