# Generated by Django 2.0.4 on 2018-11-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20181117_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Is this the main product of this type to be displayed on the products page?'),
        ),
    ]
