# Generated by Django 2.1 on 2018-11-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20181120_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_id',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('red', 'red'), ('green', 'green'), ('light-green', 'light-green'), ('blue', 'blue'), ('light-blue', 'light-blue'), ('brown', 'brown'), ('tan', 'tan'), ('white', 'white'), ('cream', 'cream'), ('orange', 'orange'), ('purple', 'purple'), ('mixed', 'mixed')], default='tan', max_length=40),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Color',
        ),
    ]
