# Generated by Django 2.1 on 2018-11-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20181121_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scent',
            name='name',
            field=models.CharField(choices=[('pumpkin', 'pumpkin'), ('mixed berry', 'mixed berry'), ('sampler', 'sampler'), ('strawberry', 'strawberry'), ('apple-cinnamon', 'apple-cinnamon'), ('cinnamon roll', 'cinnamon roll')], max_length=40),
        ),
    ]
