# Generated by Django 2.1.7 on 2019-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20190524_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
